### ISSUE TITLE
Hit sounds is lagging

### ISSUE THREAD

**Issue by traoearth** [Yasu3D/MercuryMapper#1]
The song audio is always faster than hit sounds. And adjust offset is not working

https://github.com/Yasu3D/MercuryMapper/assets/82272385/ba9ecdfc-b658-470c-ba7c-54d20102fa3d

**Comment by Yasu3D** [comment]
Small mistake on my side, the option for Hitsound Offset in the Audio tab is labeled as "R-Note Hitsound" because I forgot to change a label. Will be fixed in 1.0.1.

Assuming your audio is properly in sync, setting that ^ to a value of +25 should line hitsounds up nicely. Will also be the new default value in 1.0.1.

The `OFFSET` & `MOVIEOFFSET` fields in Chart Info do not affect playback, they're only for the game. And I suggest you avoid using them in favor of actually synchronising audio/video manually.

**Comment by traoearth** [comment]
Got that. But sync audio manually is more troublesome than sync it in MercuryMapper....

**Comment by Yasu3D** [comment]
It's easier and more accurate to sync audio in audacity or any other DAW.
